import type { Question } from "@/lib/types";

// Second question batch: EU AI Act article-level detail, ML fundamentals, privacy harms,
// standards, and crossover law.
//
// PROVENANCE: this batch mixes items written for this project with items adapted from
// community-shared AIGP study banks circulated by other candidates, including the bank
// shared by "Dr. David". Items adapted from those banks carry src: "community"; items
// written for this project carry src: "authored". Attribution to a specific original
// author is not possible at item level because the banks circulate without per-item
// bylines. See Credits in README.md. No official IAPP exam content is reproduced here. If you authored an item
// here and want it credited differently or removed, open an issue.
function o(label: string, text: string, isCorrect = false, sort = 0) {
  return { label, text, isCorrect, sort };
}

type Q = Omit<Question, "options"> & { options: ReturnType<typeof o>[] };

const raw: Array<{
  id: string;
  c: string;
  type: Question["type"];
  d: 1 | 2 | 3;
  stem: string;
  opts: [string, boolean][];
  why: string;
  wrong?: Record<string, string>;
  strat?: string;
  trap?: Question["trapType"];
  bok: string;
  src?: Question["source"];
  multi?: boolean;
}> = [
  // ───────── DOMAIN I — Foundations / AI & ML fundamentals ─────────
  { id: "x-i-a-1", c: "i-a", type: "recall", d: 1, stem: "Which is a defining requirement of supervised learning?", opts: [["Training data paired with known labels", true], ["Unlabeled data grouped by similarity", false], ["Rewards earned from environment interaction", false], ["No predefined output variable", false]], why: "Supervised learning trains on labeled data to predict labels for new cases.", wrong: { B: "That's unsupervised (clustering).", C: "That's reinforcement learning.", D: "Supervised learning has a defined target." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-2", c: "i-a", type: "recall", d: 1, stem: "Within machine learning, which term refers to the learned representation of patterns and relationships in the data?", opts: [["Algorithm", false], ["Model", true], ["Corpus", false], ["Inference", false]], why: "The model is the learned representation; the algorithm is the method that produces it.", wrong: { A: "The algorithm is the training method.", C: "A corpus is the dataset.", D: "Inference is running the model on new input." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-3", c: "i-a", type: "recall", d: 1, stem: "Deep Blue defeating Kasparov at chess in 1997 best exemplifies which category of AI by capability?", opts: [["Artificial General Intelligence", false], ["Artificial Super Intelligence", false], ["Artificial Narrow Intelligence", true], ["Broad Artificial Intelligence", false]], why: "A system mastering one task is narrow (weak) AI.", wrong: { A: "AGI is human-level across tasks (hypothetical).", B: "ASI exceeds human ability (hypothetical).", D: "Not a standard category." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-4", c: "i-a", type: "recall", d: 1, stem: "A drone maps terrain without a human pilot, adjusting its path in real time. Which shared feature of AI definitions does this best illustrate?", opts: [["Autonomy", true], ["Consciousness", false], ["Natural intelligence", false], ["Emotional reasoning", false]], why: "Acting without human input and self-adjusting demonstrates autonomy.", wrong: { B: "AI is not conscious.", C: "It's artificial, not natural.", D: "No emotion is involved." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-5", c: "i-a", type: "recall", d: 2, stem: "A bank wants to predict the exact dollar amount of loan defaults from customer data. Which supervised learning task fits?", opts: [["Regression", true], ["Logistic regression", false], ["Classification", false], ["Reinforcement learning", false]], why: "Predicting a continuous numeric value is a regression task.", wrong: { B: "Logistic regression predicts categories, not amounts.", C: "Classification predicts discrete classes.", D: "RL is reward-based learning." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-6", c: "i-a", type: "recall", d: 2, stem: "A spam filter sorts email into 'spam' or 'not spam.' Which algorithm is designed for this binary classification?", opts: [["Logistic regression", true], ["Linear regression", false], ["K-means clustering", false], ["Principal component analysis", false]], why: "Logistic regression is the classic binary-classification algorithm.", wrong: { B: "Linear regression predicts continuous values.", C: "K-means is unsupervised clustering.", D: "PCA is dimensionality reduction." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-7", c: "i-a", type: "recall", d: 2, stem: "A team wants to improve image recognition with a model that excels at spatial patterns. Which architecture fits best?", opts: [["Convolutional Neural Network (CNN)", true], ["Recurrent Neural Network (RNN)", false], ["Transformer", false], ["Decision tree", false]], why: "CNNs excel at spatial/image pattern recognition.", wrong: { B: "RNNs handle sequences.", C: "Transformers handle sequence/attention tasks.", D: "Decision trees are rule-based." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-8", c: "i-a", type: "recall", d: 2, stem: "An auditor reviews a 'black box' system of five neural-network layers and cannot tell how it reached its conclusion. What type of model is this?", opts: [["Deep learning", true], ["Decision tree", false], ["Linear regression", false], ["Logistic regression", false]], why: "Multi-layer, opaque neural networks are deep learning models.", wrong: { B: "Decision trees are explainable.", C: "Linear regression is interpretable.", D: "Logistic regression is interpretable." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-9", c: "i-a", type: "distinction", d: 2, stem: "A security team reviews an explainable model that behaves like a 'Q&A flowchart' but is unstable because small data changes heavily affect it. What algorithm is this?", opts: [["Decision tree", true], ["Deep learning", false], ["Reinforcement learning", false], ["Computer vision", false]], why: "Decision trees are explainable flowcharts but high-variance (small data changes alter the tree).", wrong: { B: "Deep learning is a black box.", C: "RL is reward-based.", D: "Computer vision is a domain, not this algorithm." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-10", c: "i-a", type: "recall", d: 2, stem: "Doctors' free-form notes must be analyzed for patterns. Which technique is most appropriate?", opts: [["Natural language processing (NLP)", true], ["Regression", false], ["Decision tree", false], ["Dimensionality reduction", false]], why: "NLP is built for analyzing free-form text.", wrong: { B: "Regression predicts numbers.", C: "Decision trees suit limited structured variables.", D: "Reduces variables; not text analysis." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-11", c: "i-a", type: "recall", d: 1, stem: "A team processes a real-time stream of user activity to drive dynamic recommendations. What data type is this?", opts: [["Streaming data", true], ["Static structured data", false], ["Unstructured static data", false], ["Cleansed labeled data", false]], why: "Continuous real-time data is streaming data.", bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-12", c: "i-a", type: "recall", d: 2, stem: "An organization analyzes social posts using a model that processes both text and the attached images/video together. This model is:", opts: [["Multimodal", true], ["Unimodal", false], ["Rule-based", false], ["Symbolic", false]], why: "Processing multiple data types (text + image/video) together = multimodal.", bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-13", c: "i-a", type: "recall", d: 2, stem: "A startup further trains a pretrained language model on legal contracts to specialize it for clause review. This is:", opts: [["Fine-tuning", true], ["Reinforcement learning", false], ["Data augmentation", false], ["Dimensionality reduction", false]], why: "Further training a pretrained model on domain data to specialize it is fine-tuning.", wrong: { B: "RL is reward-based.", C: "Augmentation expands training data.", D: "Reduces variables." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-14", c: "i-a", type: "recall", d: 1, stem: "Robotic process automation (RPA) is best described as software that:", opts: [["Mimics human steps to automate tasks and reduce human intervention", true], ["Requires constant human operation for every task", false], ["Is a deep neural network for vision", false], ["Generates novel creative content", false]], why: "RPA mimics human actions to automate repetitive tasks, decreasing human effort.", bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-a-15", c: "i-a", type: "distinction", d: 2, stem: "A model derives someone's likely religion from unrelated purchase history. Which privacy harm to individuals is this?", opts: [["Inference", true], ["Aggregation", false], ["Secondary use", false], ["Incorporation into training data", false]], why: "Deriving a new (sensitive) attribute from other data is an inference harm.", wrong: { B: "Aggregation is combining datasets.", C: "Secondary use is reusing data for a new purpose.", D: "Different harm." }, bok: "Domain I, Competency A", src: "community" },
  { id: "x-i-b-1", c: "i-b", type: "distinction", d: 2, stem: "A firm sets up a diverse, cross-functional governance body to monitor its algorithms. Which ethical-risk control does this represent?", opts: [["Oversight", true], ["Ethical principles", false], ["Policies and procedures", false], ["Transparency", false]], why: "A standing cross-functional body that monitors algorithms is an oversight control.", wrong: { B: "Principles are values, not the body.", C: "Policies are written rules.", D: "Transparency is disclosure." }, bok: "Domain I, Competency B", src: "community" },
  { id: "x-i-b-2", c: "i-b", type: "recall", d: 1, stem: "Human-centered AI (HCAI) is best described as AI that:", opts: [["Augments human ability and preserves human control", true], ["Replaces humans wherever possible", false], ["Maximizes autonomy with no human in the loop", false], ["Optimizes only for efficiency", false]], why: "HCAI puts people before machines, augmenting rather than displacing, preserving human control.", bok: "Domain I, Competency B", src: "community" },
  { id: "x-i-c-1", c: "i-c", type: "best", d: 2, stem: "A firm finds an AI use case carries high privacy risk and has limited resources. How should it allocate resources?", opts: [["Allocate more resources because higher risk requires more investment", true], ["Reduce resources to cut potential non-compliance cost", false], ["Maintain standard levels for consistency", false], ["Cut resources to prioritize higher-value projects", false]], why: "Risk-based governance directs more resources to higher-risk use cases.", wrong: { B: "Under-resourcing a high-risk project increases exposure.", C: "Ignores the elevated risk.", D: "Deprioritizing a high-risk project is the opposite of risk-based." }, trap: "wrong-economics", bok: "Domain I, Competency C", src: "community" },
  { id: "x-i-c-2", c: "i-c", type: "best", d: 2, stem: "Which best balances innovation with governance?", opts: [["Encourage experimentation within oversight, risk management, and compliance guardrails", true], ["Prioritize innovation and skip governance to move fast", false], ["Freeze all AI work until every risk is eliminated", false], ["Delegate all judgment to the model", false]], why: "Innovation must be balanced with oversight; a culture of innovation without governance breeds biased models and breaches.", trap: "absolute", bok: "Domain I, Competency C", src: "authored" },

  // ───────── DOMAIN II — Laws / Standards / Frameworks ─────────
  { id: "x-ii-a-1", c: "ii-a", type: "recall", d: 2, stem: "A vendor collects more user data than needed to deliver its service. Which Fair Information Practice is most directly violated?", opts: [["Data minimization", true], ["Notice/openness", false], ["Use limitation", false], ["Accountability", false]], why: "Collecting beyond what's necessary violates data minimization.", wrong: { B: "Notice is about disclosure.", C: "Use limitation governs how collected data is used.", D: "Accountability is about responsibility for compliance." }, bok: "Domain II, Competency A", src: "community" },
  { id: "x-ii-a-2", c: "ii-a", type: "recall", d: 1, stem: "Privacy by Design (PbD) was developed by:", opts: [["Ann Cavoukian", true], ["Daniel Solove", false], ["Helen Nissenbaum", false], ["Latanya Sweeney", false]], why: "Ann Cavoukian developed Privacy by Design and its 7 foundational principles.", bok: "Domain II, Competency A", src: "community" },
  { id: "x-ii-a-3", c: "ii-a", type: "role", d: 2, stem: "Under GDPR Article 22, an exception to the general prohibition on solely automated decisions with significant effects includes:", opts: [["Necessity for performance of a contract", true], ["Implicit consent of the data subject", false], ["Marketing convenience for the controller", false], ["Cost savings for the processor", false]], why: "Art. 22 exceptions: contract necessity, authorizing law, or explicit consent.", wrong: { B: "Consent must be explicit, not implicit.", C: "Not an exception.", D: "Not an exception." }, trap: "synonym-bait", bok: "Domain II, Competency A", src: "community" },
  { id: "x-ii-a-4", c: "ii-a", type: "recall", d: 2, stem: "A company keeps customer data indefinitely, even after account deletion. What privacy risk is this?", opts: [["Data persistence", true], ["Data repurposing", false], ["Spillover data", false], ["Data inference", false]], why: "Retaining data beyond its need/lifecycle is data persistence (a retention failure).", bok: "Domain II, Competency A", src: "community" },
  { id: "x-ii-a-5", c: "ii-a", type: "distinction", d: 2, stem: "An employee feels watched by monitoring software even though the data is never misused. What privacy harm is this?", opts: [["Subjective harm", true], ["Objective harm", false], ["Economic harm", false], ["Data persistence", false]], why: "The felt sense of surveillance, absent misuse, is a subjective privacy harm.", wrong: { B: "Objective harm requires actual adverse use of data.", C: "No financial loss is described.", D: "Unrelated.", }, bok: "Domain II, Competency A", src: "community" },
  { id: "x-ii-b-1", c: "ii-b", type: "recall", d: 2, stem: "In Thaler v. Vidal, U.S. courts held that:", opts: [["Only humans can be named inventors on patents", true], ["Pretrained AI counts as prior art", false], ["AI vendors are joint patent holders", false], ["AI cannot generate copyrightable text", false]], why: "Thaler v. Vidal held an AI cannot be a named inventor — only a human.", bok: "Domain II, Competency B", src: "community" },
  { id: "x-ii-b-2", c: "ii-b", type: "distinction", d: 2, stem: "An AI hiring tool unintentionally rejects older applicants at higher rates. This is best characterized as:", opts: [["Adverse (disparate) impact", true], ["Disparate treatment", false], ["Reasonable accommodation failure", false], ["ADA disability inquiry violation", false]], why: "Unintentional higher rejection of a protected group is disparate (adverse) impact.", wrong: { B: "Disparate treatment is intentional.", C: "Accommodation relates to disability adjustments.", D: "ADA inquiry rules are different." }, bok: "Domain II, Competency B", src: "community" },
  { id: "x-ii-b-3", c: "ii-b", type: "recall", d: 1, stem: "The FTC's authority to police 'unfair or deceptive acts or practices' comes from:", opts: [["Section 5 of the FTC Act", true], ["The Civil Rights Act of 1964", false], ["COPPA", false], ["Section 230 of the CDA", false]], why: "FTC Act §5 grants the unfair/deceptive-practices authority, applied to AI claims.", bok: "Domain II, Competency B", src: "community" },
  { id: "x-ii-b-4", c: "ii-b", type: "recall", d: 2, stem: "An AI image generator trains on news outlets' copyrighted works without permission, prompting lawsuits. Which risk category applies?", opts: [["IP infringement", true], ["Vendor-related", false], ["Economic", false], ["Operational", false]], why: "Using copyrighted works without permission is an intellectual-property infringement risk.", bok: "Domain II, Competency B", src: "community" },
  { id: "x-ii-c-1", c: "ii-c", type: "role", d: 2, stem: "Under the EU AI Act, Article 4 'AI literacy' obligations apply to:", opts: [["Providers and deployers of AI, regardless of risk level", true], ["Only providers of high-risk systems", false], ["Only deployers of GPAI models", false], ["Only public-sector deployers", false]], why: "Art. 4 AI literacy applies to providers and deployers across the board.", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-2", c: "ii-c", type: "recall", d: 2, stem: "A GPAI model is presumed to carry systemic risk when training compute exceeds:", opts: [["10^25 FLOPs", true], ["10^15 FLOPs", false], ["10^20 FLOPs", false], ["10^30 FLOPs", false]], why: "The EU AI Act sets the systemic-risk presumption at >10^25 FLOPs of training compute.", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-3", c: "ii-c", type: "role", d: 2, stem: "A company puts its own brand on a third party's high-risk AI system and markets it. Under the EU AI Act it:", opts: [["Becomes the provider and assumes provider obligations", true], ["Stays a deployer with no provider duties", false], ["Is only a distributor", false], ["Shares identical status with the original provider automatically", false]], why: "Rebranding a high-risk system (Art. 25) makes the actor a provider with full obligations.", trap: "none", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-4", c: "ii-c", type: "best", d: 2, stem: "Under EU AI Act Article 15, which practice aligns with the accuracy/robustness/cybersecurity duty for high-risk AI?", opts: [["Ensure resilience to unseen data and protect against adversarial attacks", true], ["Allow post-market learning to create unchecked feedback loops", false], ["Accept data-poisoning risk as unavoidable", false], ["Measure accuracy only via user satisfaction surveys", false]], why: "Art. 15 requires resilience to unexpected inputs and protection against adversarial manipulation.", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-5", c: "ii-c", type: "best", d: 2, stem: "Under EU AI Act Article 20, a provider that finds a high-risk system non-compliant after deployment must:", opts: [["Immediately bring it into compliance, withdraw, disable, or recall, and inform relevant parties", true], ["Notify the deployer but keep operating unchanged", false], ["Wait for the next audit cycle", false], ["Postpone until market demand falls", false]], why: "Art. 20 requires immediate corrective action (fix/withdraw/disable/recall) plus notification.", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-6", c: "ii-c", type: "recall", d: 2, stem: "Which GPAI providers get partial exemption from technical-documentation/transparency duties under the EU AI Act?", opts: [["Free and open-source GPAI with public parameters, weights, and usage details", true], ["Any provider labeling its system 'educational only'", false], ["All providers located outside the EU", false], ["Providers who simply decline to share training data", false]], why: "Open-source GPAI (public weights/usage) gets partial exemptions — unless the model has systemic risk.", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-7", c: "ii-c", type: "role", d: 2, stem: "An Annex III system can avoid high-risk classification under Article 6(3) if it:", opts: [["Performs only a narrow procedural task and poses no significant risk", true], ["Is priced below a market threshold", false], ["Is open-source under any license", false], ["Operates only inside the EU", false]], why: "Art. 6(3) carves out narrow-procedural-task systems — unless they profile individuals.", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-8", c: "ii-c", type: "not", d: 2, stem: "Which EU AI Act violation does NOT fall in the top €35M/7% penalty tier?", opts: [["Supplying incorrect information to a notified body", true], ["Operating a social-scoring system", false], ["Untargeted scraping of facial images", false], ["Deploying a prohibited manipulative AI system", false]], why: "Supplying incorrect info sits in the lowest tier (€7.5M/1%); the others are prohibited practices (top tier).", trap: "true-but-irrelevant", bok: "Domain II, Competency C", src: "community" },
  { id: "x-ii-c-9", c: "ii-c", type: "recall", d: 2, stem: "Under South Korea's AI Basic Act, the first step for an operator launching a loan-evaluation AI is to:", opts: [["Self-assess whether it qualifies as 'high-impact AI' before deployment", true], ["Obtain notified-body pre-approval", false], ["Pay administrative fines in advance", false], ["Publish the training data", false]], why: "The Act requires operators to self-assess high-impact status before deployment; loans are a high-impact domain.", wrong: { B: "Korea has no mandatory third-party conformity assessment.", C: "Absurd.", D: "Not required." }, bok: "Domain II, Competency C", src: "authored" },
  { id: "x-ii-c-10", c: "ii-c", type: "best", d: 2, stem: "A platform hosting AI image tools asks how the US Take It Down Act affects it. Best summary:", opts: [["It targets non-consensual intimate imagery (incl. AI deepfakes); covered platforms must remove flagged content within 48 hours", true], ["It bans all generative-image AI in the US", false], ["It applies only to social media, never to AI developers", false], ["It is a voluntary framework with no enforcement", false]], why: "The Take It Down Act criminalizes NCII (incl. deepfakes) and requires 48-hour platform takedown; FTC enforces.", bok: "Domain II, Competency C", src: "authored" },
  { id: "x-ii-d-1", c: "ii-d", type: "not", d: 1, stem: "Which is NOT a NIST AI RMF characteristic of trustworthy AI?", opts: [["Profit-maximizing", true], ["Valid and reliable", false], ["Privacy-enhanced", false], ["Secure and resilient", false]], why: "'Profit-maximizing' is not a trustworthy-AI characteristic.", bok: "Domain II, Competency D", src: "community" },
  { id: "x-ii-d-2", c: "ii-d", type: "recall", d: 1, stem: "Which NIST AI RMF function cultivates a risk-management culture and informs the other three?", opts: [["Govern", true], ["Map", false], ["Measure", false], ["Manage", false]], why: "GOVERN sets the culture/policies and informs MAP, MEASURE, MANAGE.", bok: "Domain II, Competency D", src: "community" },
  { id: "x-ii-d-3", c: "ii-d", type: "recall", d: 2, stem: "ISO/IEC 42001:2023 is a 'Type A' standard, meaning it:", opts: [["Can be certified by a third party (a management-system standard)", true], ["Applies only to high-risk AI", false], ["Is mandatory in the EU", false], ["Replaces ISO/IEC 27001", false]], why: "ISO 42001 is a certifiable AI management-system standard (the 'ISO 27001 for AI').", bok: "Domain II, Competency D", src: "community" },
  { id: "x-ii-d-4", c: "ii-d", type: "recall", d: 2, stem: "ISO/IEC 42005 provides structured guidance for performing:", opts: [["AI system impact assessments", true], ["AI management-system audits", false], ["AI conformity assessments", false], ["AI risk scoring only", false]], why: "ISO 42005 covers AI system impact assessments.", bok: "Domain II, Competency D", src: "community" },
  { id: "x-ii-d-5", c: "ii-d", type: "distinction", d: 2, stem: "In AI governance, the relationship between principles and frameworks is best described as:", opts: [["Frameworks operationalize principles", true], ["Principles operationalize frameworks", false], ["They are interchangeable", false], ["Frameworks replace principles in practice", false]], why: "Principles are the 'why/what'; frameworks (NIST, ISO) operationalize them into 'how.'", bok: "Domain II, Competency D", src: "community" },
  { id: "x-ii-d-6", c: "ii-d", type: "recall", d: 2, stem: "NIST's ARIA program is focused on:", opts: [["Assessing risks and impacts of AI", true], ["Publishing AI ethics guidelines", false], ["Certifying AI management systems", false], ["Setting binding AI law", false]], why: "ARIA = Assessing Risks and Impacts of AI; its core is the AI Risk Assessment Framework.", bok: "Domain II, Competency D", src: "community" },

  // ───────── DOMAIN III — Govern Development ─────────
  { id: "x-iii-a-1", c: "iii-a", type: "recall", d: 2, stem: "'Ethics by Design' should be applied at which lifecycle phase?", opts: [["Plan and design (earliest)", true], ["Deployment", false], ["Decommissioning", false], ["Only after an incident", false]], why: "Ethics by Design means building ethics in from the start — the plan and design phase.", trap: "premature", bok: "Domain III, Competency A", src: "community" },
  { id: "x-iii-a-2", c: "iii-a", type: "best", d: 2, stem: "Why quantify the harm an AI system could cause with a scoring tool?", opts: [["To choose a risk response based on the organization's risk tolerance", true], ["To make the organization immune to all future risk", false], ["To shift risk from legal to operational categories", false], ["To remove the need for an impact assessment", false]], why: "Quantifying risk lets you select an appropriate response against your risk tolerance.", trap: "absolute", bok: "Domain III, Competency A", src: "community" },
  { id: "x-iii-a-3", c: "iii-a", type: "best", d: 2, stem: "A team has identified and quantified risks for a new AI tool. The most immediate benefit is that it:", opts: [["Enables selection of appropriate controls to govern the risks", true], ["Guarantees business value exceeds any fines", false], ["Removes the need for a cross-functional team", false], ["Guarantees full autonomy of the system", false]], why: "Risk identification/quantification feeds control selection.", bok: "Domain III, Competency A", src: "community" },
  { id: "x-iii-b-1", c: "iii-b", type: "recall", d: 2, stem: "A malicious actor inserts corrupted data into a training set to degrade future predictions. Which attack is this?", opts: [["Data poisoning", true], ["Model evasion", false], ["Membership inference", false], ["Model extraction", false]], why: "Corrupting the training set is data poisoning.", wrong: { B: "Evasion crafts malicious inputs at inference.", C: "Inference reveals training membership.", D: "Extraction steals the model." }, bok: "Domain III, Competency B", src: "community" },
  { id: "x-iii-b-2", c: "iii-b", type: "recall", d: 1, stem: "Faced with inconsistent data from many sources (text, images, spreadsheets), which 'V' of big data is the core challenge?", opts: [["Variety", true], ["Volume", false], ["Velocity", false], ["Veracity", false]], why: "Many different formats/sources is the Variety dimension.", wrong: { B: "Volume = amount.", C: "Velocity = speed.", D: "Veracity = trustworthiness." }, bok: "Domain III, Competency B", src: "community" },
  { id: "x-iii-b-3", c: "iii-b", type: "distinction", d: 2, stem: "Three hospitals want a shared model without pooling raw patient records. Which technique fits?", opts: [["Federated learning", true], ["Differential privacy", false], ["Homomorphic encryption", false], ["Pseudonymization", false]], why: "Federated learning trains at each site; raw data never moves.", wrong: { B: "Diff-privacy adds noise but doesn't itself prevent data movement.", C: "Computes on encrypted data; not the core fit here.", D: "Only de-identifies." }, bok: "Domain III, Competency B", src: "community" },
  { id: "x-iii-b-4", c: "iii-b", type: "best", d: 2, stem: "A bank trains a model on EU customer data sourced across France and Germany. What must happen FIRST?", opts: [["Review where data originates/transfers and the controlling data-protection laws before processing", true], ["Remove outliers and clean the data", false], ["Build the model to the client's satisfaction", false], ["Tune hyperparameters", false]], why: "In cross-border scenarios, confirm the law allows the data movement/processing before anything else.", trap: "premature", bok: "Domain III, Competency B", src: "authored" },
  { id: "x-iii-c-1", c: "iii-c", type: "best", d: 2, stem: "Outputs start drifting from expected patterns months after launch. Which monitoring focus best catches this?", opts: [["Data/model drift checks", true], ["Code reviews", false], ["Hardware audits", false], ["User-training tests", false]], why: "Drift detection in ongoing monitoring catches post-deployment degradation.", bok: "Domain III, Competency C", src: "community" },
  { id: "x-iii-c-2", c: "iii-c", type: "recall", d: 2, stem: "What is the recognized best-practice artifact for forecasting and limiting a model's secondary or unintended uses?", opts: [["The model card", true], ["The marketing brief", false], ["The data-retention schedule", false], ["The org chart", false]], why: "Model cards document purpose, performance, limitations, and intended use — used to forecast/limit misuse.", bok: "Domain III, Competency C", src: "community" },

  // ───────── DOMAIN IV — Govern Deployment & Use ─────────
  { id: "x-iv-a-1", c: "iv-a", type: "distinction", d: 1, stem: "A returns desk uses AI to match an uploaded customer photo against the product catalog. This use case is:", opts: [["Recognition", true], ["Detection", false], ["Personalization", false], ["Optimization", false]], why: "Matching input to a known catalog/identity is recognition.", wrong: { B: "Detection finds anomalies/events.", C: "Personalization builds a unique experience from a profile.", D: "Optimization improves a process." }, bok: "Domain IV, Competency A", src: "community" },
  { id: "x-iv-a-2", c: "iv-a", type: "distinction", d: 1, stem: "A streaming app builds each subscriber a unique homepage from their viewing history. This use case is:", opts: [["Personalization", true], ["Recognition", false], ["Detection", false], ["Optimization", false]], why: "A unique experience built from an individual profile is personalization.", bok: "Domain IV, Competency A", src: "community" },
  { id: "x-iv-a-3", c: "iv-a", type: "recall", d: 1, stem: "A company runs a model on smartphones to cut latency and keep user data local. This deployment is:", opts: [["Edge", true], ["Cloud", false], ["On-premise", false], ["Local API only", false]], why: "On-device processing to cut latency and keep data local is edge deployment.", bok: "Domain IV, Competency A", src: "community" },
  { id: "x-iv-a-4", c: "iv-a", type: "recall", d: 1, stem: "A developer needs code + dependencies to run identically in cloud and on-prem. They should use:", opts: [["Containers", true], ["Manual installs", false], ["Hardware upgrades", false], ["API routing rules", false]], why: "Containers package code + dependencies for consistent runs across environments.", bok: "Domain IV, Competency A", src: "community" },
  { id: "x-iv-a-5", c: "iv-a", type: "recall", d: 1, stem: "A firm adopts a closed model whose code and parameters it cannot inspect. This is a:", opts: [["Proprietary model", true], ["Open-source model", false], ["Local rules engine", false], ["Public dataset tool", false]], why: "Closed, non-inspectable code/parameters describe a proprietary model.", bok: "Domain IV, Competency A", src: "community" },
  { id: "x-iv-a-6", c: "iv-a", type: "distinction", d: 2, stem: "A 47-country bank lets each country manage AI risk locally while a central committee sets policy and handles top escalations. This governance model is:", opts: [["Hybrid", true], ["Centralized", false], ["Decentralized", false], ["Outsourced", false]], why: "Local execution + central policy/escalation = hybrid (best for large multinationals).", wrong: { B: "Centralized = all at HQ.", C: "Decentralized = no central coordination.", D: "Not a governance model." }, bok: "Domain IV, Competency A", src: "community" },
  { id: "x-iv-b-1", c: "iv-b", type: "not", d: 2, stem: "Reviewing an OPEN-SOURCE model's agreement for privacy/IP compliance, which term is LEAST critical to that goal?", opts: [["The vendor's logo and co-marketing rights", true], ["Training-data ownership and usage rights", false], ["Output ownership", false], ["Obligations to share derivative works", false]], why: "Branding/co-marketing rights don't bear on privacy/IP; the others drive privacy and IP exposure.", trap: "true-but-irrelevant", bok: "Domain IV, Competency B", src: "community" },
  { id: "x-iv-b-2", c: "iv-b", type: "best", d: 2, stem: "A team says 'our tech stack (frameworks/libraries) determines which laws apply.' The best correction is:", opts: [["Applicable law is driven by jurisdiction, sector, data type, and use — not the tech stack", true], ["Correct — the stack determines the law", false], ["No laws apply to internally built tools", false], ["Only copyright law ever applies to AI", false]], why: "Law follows jurisdiction/sector/data/use, not the technology stack itself.", bok: "Domain IV, Competency B", src: "community" },
  { id: "x-iv-b-3", c: "iv-b", type: "recall", d: 2, stem: "Before deploying a recruitment AI in the EU market, a high-risk system requires:", opts: [["A conformity assessment", true], ["Only a privacy policy update", false], ["No assessment if a human reviews outputs", false], ["A marketing review", false]], why: "High-risk systems require a conformity assessment before EU market deployment.", bok: "Domain IV, Competency B", src: "authored" },
  { id: "x-iv-c-1", c: "iv-c", type: "not", d: 2, stem: "Which is NOT a valid trigger in a deactivation/localization policy?", opts: [["A desire to protect the product's profit margin", true], ["A new regulatory requirement the system can't meet", false], ["Significant, unmitigated performance failures", false], ["A legal order to stop processing in a jurisdiction", false]], why: "Profit protection is never a valid deactivation trigger; regulatory/performance/legal reasons are.", trap: "wrong-economics", bok: "Domain IV, Competency C", src: "community" },
  { id: "x-iv-c-2", c: "iv-c", type: "best", d: 2, stem: "A provider must take an AI feature offline in one country during regulatory talks while keeping it live elsewhere, ideally without a redeploy. Best mechanism:", opts: [["Jurisdiction-scoped feature flags", true], ["Permanently delete the model", false], ["Email users to ignore the feature", false], ["Wait for the next major release", false]], why: "Feature flags toggle/localize a feature by jurisdiction without a full redeploy.", bok: "Domain IV, Competency C", src: "community" },
  { id: "x-iv-c-3", c: "iv-c", type: "best", d: 2, stem: "Customers are anxious about a new AI assistant. The best external-communication approach is to:", opts: [["Give comprehensive, accessible info on both capabilities AND limitations", true], ["Emphasize only the strengths to build confidence", false], ["Decline to explain how it works", false], ["Send all questions to the vendor", false]], why: "Balanced transparency about capabilities and limitations builds trust.", trap: "absolute", bok: "Domain IV, Competency C", src: "community" },
  { id: "x-iv-c-4", c: "iv-c", type: "best", d: 2, stem: "A fraud model produces excess false positives from drift; the team applies a feasible threshold fix promptly. What best justifies keeping it running?", opts: [["A feasible mitigation was identified and applied in a timely manner", true], ["It has been profitable for years", false], ["Migrating to a replacement is burdensome", false], ["Its limitations are documented for customers", false]], why: "Timely feasible mitigation justifies continued operation; profit/burden don't, and documentation alone doesn't fix performance.", trap: "wrong-economics", bok: "Domain IV, Competency C", src: "community" },
];

export const questionsExtra: Question[] = raw.map((r) => {
  const opts = r.opts.map(([text, isCorrect], i) => o(String.fromCharCode(65 + i), text, isCorrect, i));
  const q: Q = {
    id: r.id,
    competencyId: r.c,
    type: r.type,
    difficulty: r.d,
    stem: r.stem,
    isMultiselect: r.multi ?? false,
    options: opts,
    correctExplanation: r.why,
    whyWrong: r.wrong ?? {},
    strategyNote: r.strat,
    trapType: r.trap ?? "none",
    bokRef: r.bok,
    source: r.src ?? "community",
  };
  return q as Question;
});
