import type { Question } from "@/lib/types";

// Third batch (Jul 2026 refresh): current-law items (EU Digital Omnibus, Colorado SB 26-189,
// TRAIGA, GPAI Code of Practice) + a heavy dose of convoluted BEST/scenario items for
// technique training. Same terse format as batch 2.
function o(label: string, text: string, isCorrect = false, sort = 0) {
  return { label, text, isCorrect, sort };
}

const raw: Array<{
  id: string;
  c: string;
  type: Question["type"];
  d: 1 | 2 | 3;
  stem: string;
  opts: [string, boolean][];
  why: string;
  wrong?: Record<string, string>;
  strat?: string;
  trap?: Question["trapType"];
  bok: string;
  src?: Question["source"];
}> = [
  // ───────── CURRENT LAW (Jul 2026) — Domain II.C ─────────
  { id: "z-ii-c-1", c: "ii-c", type: "recall", d: 2, stem: "Under the EU Digital Omnibus on AI (in force July 2026), obligations for stand-alone Annex III high-risk systems now apply from:", opts: [["2 December 2027", true], ["2 August 2026", false], ["2 August 2027", false], ["They were repealed entirely", false]], why: "The Omnibus deferred Annex III high-risk obligations from 2 Aug 2026 to 2 Dec 2027 (Annex I to 2 Aug 2028).", wrong: { B: "The original date — superseded by the Omnibus.", C: "That was the original Annex I date.", D: "Deferred, not repealed." }, bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-2", c: "ii-c", type: "not", d: 3, stem: "Which EU AI Act obligation was NOT deferred by the 2026 Digital Omnibus?", opts: [["Article 50 transparency duties (chatbot disclosure, AI-content labeling)", true], ["High-risk duties for Annex III recruitment systems", false], ["High-risk duties for Annex III credit-scoring systems", false], ["High-risk duties for AI in Annex I regulated products", false]], why: "Art. 50 transparency still applies from 2 Aug 2026; the high-risk timelines (Annex III → Dec 2027, Annex I → Aug 2028) were deferred.", strat: "Omnibus changed the HIGH-RISK dates only. Prohibitions, GPAI, penalties, and transparency stayed put.", bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-3", c: "ii-c", type: "best", d: 3, stem: "In September 2026 an EU consumer app launches a generative-AI chatbot. Compliance asks what applies NOW versus later. The most accurate answer is:", opts: [["Article 50 transparency applies now (disclose the AI, label AI content); Annex III high-risk duties, if the app ever qualifies, apply from December 2027", true], ["Nothing applies until December 2027 because of the Omnibus", false], ["Full high-risk conformity assessment applies immediately", false], ["Only the GDPR applies to chatbots", false]], why: "Post-Omnibus: transparency from 2 Aug 2026; deferred Annex III duties from 2 Dec 2027.", wrong: { B: "The Omnibus did not defer transparency, prohibitions, or GPAI rules.", C: "A consumer chatbot is a transparency-tier system, not automatically high-risk.", D: "GDPR applies too, but Art. 50 is squarely in scope." }, trap: "absolute", bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-4", c: "ii-c", type: "recall", d: 2, stem: "As of 2026, Colorado's AI regulation is best described as:", opts: [["SB 26-189 — an ADMT law: disclosures, adverse-outcome explanations, correction rights, and human review for automated tech that materially influences consequential decisions (eff. 1 Jan 2027)", true], ["SB 24-205 — high-risk AI and algorithmic discrimination duties, in force since June 2026", false], ["A ban on all automated decision-making", false], ["Colorado has no AI-specific law", false]], why: "The original AI Act was repealed before taking effect; SB 26-189 (signed 14 May 2026) replaces it, effective 1 Jan 2027.", wrong: { B: "SB 24-205 never took effect — repealed and replaced.", C: "It regulates, not bans.", D: "SB 26-189 exists." }, bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-5", c: "ii-c", type: "distinction", d: 3, stem: "The cleanest one-line contrast between Texas TRAIGA and Colorado SB 26-189 is:", opts: [["TRAIGA is intent-based (liability for intentional harms); SB 189 is impact/transparency-based (duties when ADMT materially influences consequential decisions)", true], ["TRAIGA covers only government AI; SB 189 covers only healthcare AI", false], ["Both copy the EU AI Act's risk tiers", false], ["TRAIGA has a private right of action; SB 189 is enforced by the FTC", false]], why: "TRAIGA generally requires intent; SB 189 attaches transparency/consumer-rights duties based on the decision's impact.", wrong: { D: "Both are AG-enforced; neither gives a private right of action (SB 189 explicitly AG-only)." }, bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-6", c: "ii-c", type: "recall", d: 2, stem: "For GPAI providers, following the AI Office's Code of Practice gives:", opts: [["A presumption of conformity with the GPAI obligations", true], ["Full immunity from penalties", false], ["Exemption from the training-content summary", false], ["High-risk classification relief", false]], why: "The GPAI Codes of Practice are the primary compliance route and carry a presumption of conformity.", trap: "absolute", bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-7", c: "ii-c", type: "role", d: 3, stem: "A US vendor sells an unchanged CV-screening model to an EU retailer, which uses it under its own authority. Post-Omnibus, when Annex III duties bite (Dec 2027), the conformity assessment is primarily the obligation of:", opts: [["The US vendor as provider (with an EU authorized representative)", true], ["The EU retailer as deployer", false], ["The retailer's IT integrator", false], ["No one — Annex III duties were repealed", false]], why: "Providers carry conformity assessment; non-EU providers need an authorized representative. The deployer has lighter use/monitor/oversight duties.", wrong: { B: "Deployers don't run the provider's conformity assessment.", D: "Deferred, not repealed." }, bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-8", c: "ii-c", type: "best", d: 3, stem: "An EU bank wants to pilot an AI credit-scoring tool in October 2026. Governance's BEST framing of the legal position is:", opts: [["Deferred Annex III duties formally bite in Dec 2027, but GDPR Art. 22, nondiscrimination law, and Art. 50 transparency apply now — build conformity-grade controls early rather than waiting", true], ["Nothing applies until December 2027, so pilot freely", false], ["Credit scoring is prohibited under Article 5", false], ["Only the bank's internal policy applies", false]], why: "The deferral moves the AI-Act high-risk deadline, not the surrounding law; best practice is building to the coming standard now.", wrong: { B: "GDPR/discrimination/consumer law never paused.", C: "Credit scoring is high-risk, not prohibited." }, trap: "wrong-economics", strat: "'Deferred' ≠ 'lawless'. IAPP rewards the answer that keeps existing law + proactive governance in view.", bok: "Domain II, Competency C", src: "authored" },

  // ───────── DOMAIN II depth ─────────
  { id: "z-ii-a-1", c: "ii-a", type: "best", d: 3, stem: "A HR platform wants to rely on 'legitimate interests' to train models on employee data across the EU. The privacy team's FIRST analytical step should be:", opts: [["A necessity-and-balancing assessment (LIA) weighing the interest against employees' rights, given the power imbalance", true], ["Send a notice email and proceed", false], ["Rely on consent collected at onboarding", false], ["Anonymize afterwards if anyone complains", false]], why: "Legitimate interests requires necessity + balancing; employment context raises power-imbalance concerns.", wrong: { C: "Employee consent is rarely freely given (power imbalance).", D: "Reactive, not by-design." }, trap: "premature", bok: "Domain II, Competency A", src: "authored" },
  { id: "z-ii-a-2", c: "ii-a", type: "recall", d: 2, stem: "Under GDPR, an applicant subject to a solely automated loan refusal is entitled to:", opts: [["Human intervention, the ability to express their view, and to contest the decision", true], ["Source code of the model", false], ["Automatic approval on appeal", false], ["Compensation without showing harm", false]], why: "Art. 22 safeguards: human intervention, express views, contest (redress).", bok: "Domain II, Competency A", src: "authored" },
  { id: "z-ii-b-1", c: "ii-b", type: "best", d: 3, stem: "A US retailer's AI pricing engine charges higher prices in ZIP codes correlated with protected classes. The clearest immediate legal exposure is:", opts: [["Discrimination/consumer-protection law (disparate impact; unfair practices)", true], ["Patent law", false], ["Export-control law", false], ["The EU AI Act", false]], why: "Proxy discrimination via ZIP codes triggers nondiscrimination and FTC §5 unfairness exposure.", wrong: { D: "No EU nexus given." }, bok: "Domain II, Competency B", src: "authored" },
  { id: "z-ii-d-1", c: "ii-d", type: "distinction", d: 2, stem: "An org wants a certifiable management-system standard for AI and a companion for impact assessment. The pair is:", opts: [["ISO/IEC 42001 + ISO/IEC 42005", true], ["ISO/IEC 27001 + ISO/IEC 22989", false], ["NIST AI RMF + OECD Principles", false], ["ISO 9001 + ISO 31000", false]], why: "42001 = certifiable AI management system; 42005 = AI system impact assessment.", wrong: { C: "Frameworks/principles, not certifiable standards." }, bok: "Domain II, Competency D", src: "authored" },
  { id: "z-ii-d-2", c: "ii-d", type: "best", d: 2, stem: "A CISO asks which NIST AI RMF function 'runs continuously underneath' the other three. Best answer:", opts: [["GOVERN — culture, policies, roles that inform MAP, MEASURE, MANAGE", true], ["MAP — because context comes first", false], ["MEASURE — because you can't manage what you don't measure", false], ["MANAGE — because action is what matters", false]], why: "GOVERN is the cross-cutting function that informs the cycle.", bok: "Domain II, Competency D", src: "authored" },

  // ───────── DOMAIN I — scenario/policy ─────────
  { id: "z-i-a-1", c: "i-a", type: "best", d: 3, stem: "A hospital's diagnostic AI is accurate overall but fails more often for patients over 80, who are underrepresented in training data. The governance framing that BEST captures the core issue is:", opts: [["A fairness and representativeness failure requiring data governance and bias testing", true], ["A pure cybersecurity gap", false], ["A cost-optimization opportunity", false], ["An IP-licensing dispute", false]], why: "Underrepresentation causing group-level performance gaps is a fairness/data-representativeness issue.", bok: "Domain I, Competency A", src: "authored" },
  { id: "z-i-a-2", c: "i-a", type: "distinction", d: 2, stem: "A generative model fabricates a convincing but false citation. This failure is best termed:", opts: [["Hallucination", true], ["Model drift", false], ["Data poisoning", false], ["Overfitting", false]], why: "Confident fabrication of false content is hallucination.", wrong: { B: "Drift is post-deployment degradation.", C: "Poisoning is an attack on training data.", D: "Overfitting is memorizing training data." }, bok: "Domain I, Competency A", src: "authored" },
  { id: "z-i-b-1", c: "i-b", type: "best", d: 3, stem: "A CEO wants a single 'AI owner' to be solely accountable so 'governance doesn't slow teams down.' The AIGP's BEST counsel is:", opts: [["Name an accountable executive AND a cross-functional governance body — single-point ownership without diverse oversight misses multifaceted AI risks", true], ["Agree — one owner, no committees", false], ["Reject ownership entirely; make everyone responsible", false], ["Outsource accountability to the model vendor", false]], why: "Accountability needs an owner plus cross-functional oversight; 'everyone responsible' = no one responsible; vendors can't own your accountability.", trap: "too-narrow", bok: "Domain I, Competency B", src: "authored" },
  { id: "z-i-c-1", c: "i-c", type: "best", d: 3, stem: "Legal wants to add AI provisions to procurement contracts. The clause set MOST specific to AI third-party risk is:", opts: [["Training-data rights, output ownership, model-update/change notification, incident cooperation, audit rights, and use restrictions", true], ["Standard payment and delivery terms", false], ["Office-access badge policies", false], ["A generic force-majeure clause", false]], why: "AI vendor risk lives in data rights, output IP, change/incident transparency, and auditability.", bok: "Domain I, Competency C", src: "authored" },
  { id: "z-i-c-2", c: "i-c", type: "ordering", d: 3, stem: "Sequence these steps for adding a generative-AI feature to an existing product: (1) map applicable laws; (2) define the use case and success criteria; (3) impact assessment; (4) design controls and human oversight; (5) pre-deployment testing incl. red teaming.", opts: [["2 → 1 → 3 → 4 → 5", true], ["1 → 2 → 3 → 4 → 5", false], ["3 → 2 → 1 → 5 → 4", false], ["2 → 3 → 5 → 4 → 1", false]], why: "Business use case first, then the laws that attach to it, then assess impact, design controls, test.", strat: "Use-case before laws (laws attach to a use), assessments before controls, controls before testing.", bok: "Domain I, Competency C", src: "authored" },

  // ───────── DOMAIN III — development scenarios ─────────
  { id: "z-iii-a-1", c: "iii-a", type: "best", d: 3, stem: "Mid-build, the data science team proposes swapping a transparent scoring model for a deep-learning model with +2% accuracy, in a regulated lending context. Governance's BEST response is:", opts: [["Weigh the accuracy gain against explainability/regulatory duties (adverse-action reasons, contestability) before approving — accuracy alone doesn't decide it", true], ["Approve — accuracy is the only metric that matters", false], ["Reject all deep learning categorically", false], ["Defer to whatever the vendor recommends", false]], why: "Regulated credit requires explainable reasons; the trade-off must be assessed, not assumed either way.", trap: "absolute", bok: "Domain III, Competency A", src: "authored" },
  { id: "z-iii-a-2", c: "iii-a", type: "best", d: 3, stem: "A product team wants to skip the AI impact assessment because 'we already did a DPIA.' The BEST correction is:", opts: [["Extend the DPIA into an AI impact assessment — privacy is one lens; AI assessment also covers fairness, safety, robustness, and societal impacts", true], ["Agree — a DPIA covers everything", false], ["Run a fully separate process that ignores the DPIA", false], ["Skip both since the vendor did testing", false]], why: "Start from the DPIA and tailor/extend to AI-specific risks — the assessments overlap but aren't identical.", trap: "synonym-bait", bok: "Domain III, Competency A", src: "authored" },
  { id: "z-iii-b-1", c: "iii-b", type: "best", d: 3, stem: "A team fine-tunes on customer support transcripts. The data step MOST specific to responsible training here is:", opts: [["Verify lawful rights to use the transcripts and scrub/limit personal data before training", true], ["Use all transcripts as-is for maximum accuracy", false], ["Buy more third-party data first", false], ["Train first, review complaints later", false]], why: "Lawful basis + minimization on training data is the core Domain III.B duty.", trap: "wrong-economics", bok: "Domain III, Competency B", src: "authored" },
  { id: "z-iii-b-2", c: "iii-b", type: "distinction", d: 2, stem: "During evaluation, a model performs brilliantly on training data but poorly on held-out data. The diagnosis is:", opts: [["Overfitting", true], ["Underfitting", false], ["Concept drift", false], ["Label leakage always", false]], why: "Great train / poor test performance = overfitting (memorization).", wrong: { B: "Underfitting fails on both.", C: "Drift is post-deployment.", D: "'Always' overreaches — leakage is one possible cause, not the definition." }, trap: "absolute", bok: "Domain III, Competency B", src: "authored" },
  { id: "z-iii-b-3", c: "iii-b", type: "best", d: 3, stem: "Bias testing before release shows the resume screener passes men at 1.4× the rate of equally qualified women. The BEST next step is:", opts: [["Diagnose the source (data, features, labels), remediate, and re-test before any release — document the process", true], ["Ship now, monitor later", false], ["Delete the gender column and declare it fixed", false], ["Lower the passing threshold for everyone", false]], why: "Fix-and-retest with documentation; removing the protected attribute doesn't remove proxies ('fairness through unawareness' fails).", wrong: { C: "Proxies (e.g., activity gaps, schools) still encode gender.", }, trap: "too-narrow", bok: "Domain III, Competency B", src: "authored" },
  { id: "z-iii-c-1", c: "iii-c", type: "best", d: 3, stem: "Post-release, an LLM feature starts leaking fragments of its system prompt under crafted inputs. The BEST immediate governance response is:", opts: [["Treat it as an incident: contain (guardrails/disable if needed), document, root-cause, and add prompt-injection tests to the red-team suite", true], ["Ignore unless customers notice", false], ["Permanently shut down the whole product line", false], ["Blame the user for prompting wrong", false]], why: "Incident-manage: contain, document, root-cause, and harden testing.", trap: "absolute", bok: "Domain III, Competency C", src: "authored" },
  { id: "z-iii-c-2", c: "iii-c", type: "recall", d: 2, stem: "The document a provider gives deployers so they can operate a high-risk system correctly is the:", opts: [["Instructions for use", true], ["Marketing datasheet", false], ["Terms of service", false], ["Model weights file", false]], why: "Providers must supply instructions for use (capabilities, limitations, oversight measures).", bok: "Domain III, Competency C", src: "authored" },
  { id: "z-iii-c-3", c: "iii-c", type: "distinction", d: 2, stem: "Quarterly, an independent team checks the AI program against policy and law, without attacking the system. This activity is:", opts: [["An audit", true], ["Red teaming", false], ["Threat modeling", false], ["Penetration testing", false]], why: "Compliance/consistency review = audit; no adversarial simulation involved.", bok: "Domain III, Competency C", src: "authored" },

  // ───────── DOMAIN IV — deployment scenarios ─────────
  { id: "z-iv-a-1", c: "iv-a", type: "best", d: 3, stem: "A hospital network must choose between a cloud LLM API and an on-prem open-weights model for clinical notes. The decision factor MOST specific to this context is:", opts: [["Data sensitivity and residency: whether PHI can leave the environment, and who can access it", true], ["Which vendor has the nicer logo", false], ["Raw benchmark scores alone", false], ["Whatever the newest model is", false]], why: "For PHI, deployment choice turns on sensitivity/residency/control; benchmarks matter but don't dominate.", bok: "Domain IV, Competency A", src: "authored" },
  { id: "z-iv-a-2", c: "iv-a", type: "distinction", d: 2, stem: "A team improves a base model's answers by retrieving company documents at query time and injecting them into the prompt. This technique is:", opts: [["Retrieval-augmented generation (RAG)", true], ["Fine-tuning", false], ["Distillation", false], ["Quantization", false]], why: "Fetching context at query time = RAG; no weights change.", wrong: { B: "Fine-tuning updates weights on new data." }, bok: "Domain IV, Competency A", src: "authored" },
  { id: "z-iv-a-3", c: "iv-a", type: "best", d: 3, stem: "Leadership wants 'an agent that acts autonomously across our systems.' The FIRST governance question should be:", opts: [["What actions may it take, with what permissions, under whose oversight — and how do we constrain and log them?", true], ["Which UI theme should it have?", false], ["Can we ship it this sprint?", false], ["Which conference should we announce it at?", false]], why: "Agentic autonomy is a permissions/oversight/logging question first.", bok: "Domain IV, Competency A", src: "authored" },
  { id: "z-iv-b-1", c: "iv-b", type: "best", d: 3, stem: "Procurement is finalizing a GenAI vendor contract. Given IP-infringement suits in the news, the MOST protective clause set is:", opts: [["Training-data warranties, IP indemnification for outputs, and clarity on output ownership/usage rights", true], ["A discount for annual prepayment", false], ["Unlimited free seats", false], ["A co-marketing commitment", false]], why: "IP exposure is managed via warranties, indemnities, and output-rights clarity.", trap: "true-but-irrelevant", bok: "Domain IV, Competency B", src: "authored" },
  { id: "z-iv-b-2", c: "iv-b", type: "best", d: 3, stem: "Before piloting a third-party fraud model, the risk team asks for 'evidence, not promises.' The BEST artifact set to request is:", opts: [["Model card, evaluation results incl. bias testing, security posture, and incident history", true], ["The sales deck", false], ["Logos of other customers", false], ["A verbal assurance of accuracy", false]], why: "Diligence runs on documentation and test evidence.", bok: "Domain IV, Competency B", src: "authored" },
  { id: "z-iv-c-1", c: "iv-c", type: "best", d: 3, stem: "After deployment, monitoring shows the model's input distribution shifting (new customer segment). Accuracy hasn't dropped yet. The BEST action is:", opts: [["Flag data drift, tighten monitoring, and schedule evaluation/possible retraining before performance degrades", true], ["Wait until accuracy visibly drops", false], ["Retrain immediately on unvalidated new data", false], ["Turn off monitoring to save cost", false]], why: "Leading-indicator drift warrants proactive evaluation — act before failure, but don't blindly retrain.", trap: "premature", bok: "Domain IV, Competency C", src: "authored" },
  { id: "z-iv-c-2", c: "iv-c", type: "best", d: 3, stem: "A customer harmed by an automated decision demands an explanation and correction. The deployer's BEST-practice response is:", opts: [["Provide a meaningful explanation, a route to human review, and correct the record if wrong — per policy and (where applicable) law", true], ["Point to the terms of service", false], ["Say the model is proprietary so nothing can be shared", false], ["Offer a coupon", false]], why: "Explanation + human review + correction is the redress pattern (GDPR Art. 22; Colorado SB 189 mirrors it).", bok: "Domain IV, Competency C", src: "authored" },
  { id: "z-iv-c-3", c: "iv-c", type: "not", d: 3, stem: "Which is NOT a sound reason to keep operating an AI system that has shown issues?", opts: [["Decommissioning would reduce this quarter's revenue", true], ["A feasible mitigation was applied promptly and verified", false], ["The issue was traced to an input pipeline bug that was fixed and re-tested", false], ["Controls now keep residual risk within the org's documented tolerance", false]], why: "Revenue never justifies running an unsafe system; the others are legitimate risk-managed reasons.", trap: "wrong-economics", bok: "Domain IV, Competency C", src: "authored" },
  { id: "z-iv-c-4", c: "iv-c", type: "recall", d: 2, stem: "A provider discovers a deployed high-risk system is non-conforming and risky. The expected action set is:", opts: [["Correct, withdraw, disable, or recall — and inform deployers and authorities", true], ["Silent hotfix only", false], ["Wait for the annual audit", false], ["Post a blog apology", false]], why: "Corrective-action duty: fix/withdraw/disable/recall + notification.", bok: "Domain IV, Competency C", src: "authored" },
  { id: "z-iv-c-5", c: "iv-c", type: "best", d: 3, stem: "An internal chatbot for HR policies starts being used by staff for legal advice. Governance's BEST framing is:", opts: [["Unintended secondary use — restate intended use, add guardrails/disclaimers, monitor prompts, and update the model card and training", true], ["Free product expansion — encourage it", false], ["Fire the users", false], ["Ignore it since it's internal", false]], why: "Scope creep beyond intended use is exactly the 'secondary/unintended use' risk to forecast and control.", bok: "Domain IV, Competency C", src: "authored" },

  // ───────── Extra current-events (II.C) ─────────
  { id: "z-ii-c-9", c: "ii-c", type: "recall", d: 2, stem: "Colorado SB 26-189 is enforced by:", opts: [["The Colorado Attorney General exclusively (no private right of action), with a 60-day cure for most violations", true], ["Private class actions", false], ["The FTC", false], ["A new Colorado AI Agency", false]], why: "AG-only enforcement as deceptive trade practices; 60-day cure unless knowing/repeated.", bok: "Domain II, Competency C", src: "authored" },
  { id: "z-ii-c-10", c: "ii-c", type: "best", d: 3, stem: "A multistate US deployer asks how to prepare for both TRAIGA and Colorado SB 189 with one program. The BEST unified approach is:", opts: [["Inventory ADMT/consequential-decision uses; implement disclosures, adverse-outcome explanations, human review; and document intent + testing — covering impact-based and intent-based regimes", true], ["Comply only with the stricter state and ignore the other", false], ["Geo-block Colorado and Texas", false], ["Wait for federal preemption", false]], why: "One governance layer — inventory, transparency, redress, documentation — satisfies both philosophies.", trap: "wrong-economics", bok: "Domain II, Competency C", src: "authored" },
];

export const questionsBatch3: Question[] = raw.map((r) => ({
  id: r.id,
  competencyId: r.c,
  type: r.type,
  difficulty: r.d,
  stem: r.stem,
  isMultiselect: false,
  options: r.opts.map(([text, isCorrect], i) => o(String.fromCharCode(65 + i), text, isCorrect, i)),
  correctExplanation: r.why,
  whyWrong: r.wrong ?? {},
  strategyNote: r.strat,
  trapType: r.trap ?? "none",
  bokRef: r.bok,
  source: r.src ?? "authored",
}));
