import type { Question } from "@/lib/types";

// Helper to build options tersely: o("A","text",true)
function o(label: string, text: string, isCorrect = false, sort = 0) {
  return { label, text, isCorrect, sort };
}

// Starter bank — IAPP-style. Mixed provenance: items marked `source: "authored"` were written
// for this project; items marked `source: "community"` are adapted from community-shared AIGP
// study banks circulated by other candidates (see Credits in README.md). No official IAPP exam
// content is reproduced here.
// Every competency is covered; all six question types represented. Growable via the seed pipeline.
export const questions: Question[] = [
  // ───────────── DOMAIN I ─────────────
  {
    id: "q-i-a-1",
    competencyId: "i-a",
    type: "distinction",
    difficulty: 2,
    stem: "A city deploys an AI tool that scans CCTV feeds to flag individuals matching a watchlist of a particular ethnic community during protests. Which category of harm does this MOST directly raise?",
    isMultiselect: false,
    options: [o("A", "Individual harm", false, 0), o("B", "Group harm", true, 1), o("C", "Organizational harm", false, 2), o("D", "Societal harm", false, 3)],
    correctExplanation: "Targeting a demographic/community is group harm.",
    whyWrong: { A: "Individual harm affects one person.", C: "Organizational harm is to the company.", D: "Societal harm (e.g., disinformation) isn't targeted at a specific group." },
    strategyNote: "Classify harm by WHO is affected, not by the technology. Surveillance 'feels' societal, but targeting a group makes it group harm.",
    trapType: "true-but-irrelevant",
    bokRef: "Domain I, Competency A",
    source: "authored",
  },
  {
    id: "q-i-a-2",
    competencyId: "i-a",
    type: "distinction",
    difficulty: 2,
    stem: "An AI vendor claims its system is 'fully transparent because we publish an explanation of every decision.' Which statement is MOST accurate?",
    isMultiselect: false,
    options: [
      o("A", "Transparency and explainability are the same property, so the claim is sound", false, 0),
      o("B", "Transparency (what happened) and explainability (how a decision was made) are distinct but mutually supporting; the vendor is conflating them", true, 1),
      o("C", "Explainability is irrelevant once transparency is achieved", false, 2),
      o("D", "Neither concept applies to AI systems", false, 3),
    ],
    correctExplanation: "NIST AI RMF §3.5: transparency answers 'what happened'; explainability answers 'how a decision was made.' Distinct, mutually supporting — not synonyms.",
    whyWrong: { A: "Treats them as interchangeable — the classic synonym-bait.", C: "Both are needed.", D: "Both apply squarely to AI." },
    strategyNote: "When two options name near-neighbor concepts, the question IS the distinction.",
    trapType: "synonym-bait",
    bokRef: "Domain I, Competency A",
    source: "authored",
  },
  {
    id: "q-i-a-3",
    competencyId: "i-a",
    type: "recall",
    difficulty: 1,
    stem: "An AI fraud-detection model performs well at launch but accuracy drops as customer behavior shifts. What is this best called?",
    isMultiselect: false,
    options: [o("A", "Model decay (drift)", true, 0), o("B", "Model evasion", false, 1), o("C", "Membership inference", false, 2), o("D", "Adversarial robustness", false, 3)],
    correctExplanation: "Performance degrading as the world changes = model decay / drift.",
    whyWrong: { B: "Evasion is an adversarial input attack.", C: "Membership inference is a privacy attack.", D: "Robustness is a desirable property, not the failure." },
    trapType: "none",
    bokRef: "Domain I, Competency A",
    source: "community",
  },
  {
    id: "q-i-b-1",
    competencyId: "i-b",
    type: "best",
    difficulty: 2,
    stem: "A 4,000-person insurer is standing up an AI governance program. Who must be involved from day one?",
    isMultiselect: false,
    options: [
      o("A", "Only the data science team, since they understand the models best", false, 0),
      o("B", "A cross-functional group anchored by privacy and security experts, expandable as AI dependencies surface", true, 1),
      o("C", "An external consultancy retained to own all AI governance decisions", false, 2),
      o("D", "The marketing team, to ensure the program supports go-to-market goals", false, 3),
    ],
    correctExplanation: "Privacy & security experts are always core; the group must be cross-functional and expandable as AI use is discovered.",
    whyWrong: { A: "Too narrow (tech-only).", C: "Outsources the thinking — governance can't be fully delegated.", D: "Irrelevant framing." },
    strategyNote: "BEST answer is the holistic, cross-functional one. Distractors trip 'too narrow' or 'abdication' wires.",
    trapType: "too-narrow",
    bokRef: "Domain I, Competency B",
    source: "authored",
  },
  {
    id: "q-i-b-2",
    competencyId: "i-b",
    type: "not",
    difficulty: 3,
    stem: "A privacy leader is CREATING the organization's AI governance structure. Which is NOT part of creating the structure itself?",
    isMultiselect: false,
    options: [
      o("A", "Determine whether an AI governance structure already exists", false, 0),
      o("B", "Identify and document who will maintain the structure", false, 1),
      o("C", "Identify the specific laws that apply to each AI use case", true, 2),
      o("D", "Identify an executive champion to sponsor the program", false, 3),
    ],
    correctExplanation: "Identifying applicable laws is an implementation activity, not part of creating the governance structure.",
    whyWrong: { A: "Structure creation step.", B: "Structure creation step.", D: "Structure creation step." },
    strategyNote: "Right concept, wrong life-cycle phase. Map each option to its stage.",
    trapType: "premature",
    bokRef: "Domain I, Competency B",
    source: "authored",
  },
  {
    id: "q-i-c-1",
    competencyId: "i-c",
    type: "best",
    difficulty: 2,
    stem: "A retailer that already uses AI for product copy now wants AI to screen job applicants. Before launching the hiring tool, which existing policy is the priority to evaluate and update?",
    isMultiselect: false,
    options: [o("A", "The marketing content policy", false, 0), o("B", "The employment nondiscrimination policy", true, 1), o("C", "The data-retention schedule for web analytics", false, 2), o("D", "The social-media brand policy", false, 3)],
    correctExplanation: "Hiring AI carries acute legal risk (ADA/EEOC/FCRA/state law), so the nondiscrimination policy is the priority.",
    whyWrong: { A: "Not the priority for a hiring use case.", C: "Not the priority.", D: "Irrelevant to hiring." },
    trapType: "none",
    bokRef: "Domain I, Competency C",
    source: "authored",
  },
  {
    id: "q-i-c-2",
    competencyId: "i-c",
    type: "best",
    difficulty: 2,
    stem: "A firm finds an AI use case carries high privacy risk. Given limited organizational resources, how should it allocate resources for this project?",
    isMultiselect: false,
    options: [
      o("A", "Reduce resources to lower the financial impact of potential non-compliance", false, 0),
      o("B", "Maintain standard resource levels to ensure operational consistency", false, 1),
      o("C", "Allocate more resources because higher risk levels require more investment", true, 2),
      o("D", "Decrease resources to prioritize projects with higher business value", false, 3),
    ],
    correctExplanation: "Risk-based governance allocates MORE resources to HIGHER-risk use cases.",
    whyWrong: { A: "Reducing resources ignores the risk.", B: "Maintaining ignores the elevated risk.", D: "Deprioritizing a high-risk project is the opposite of risk-based." },
    trapType: "none",
    bokRef: "Domain I, Competency C",
    source: "community",
  },

  // ───────────── DOMAIN II ─────────────
  {
    id: "q-ii-a-1",
    competencyId: "ii-a",
    type: "best",
    difficulty: 2,
    stem: "An EU bank's AI denies a loan via a solely automated decision with significant effect. The applicant wants it reviewed. Under GDPR Article 22, the applicant's primary avenue is:",
    isMultiselect: false,
    options: [
      o("A", "There is no recourse for automated decisions", false, 0),
      o("B", "Redress — request human intervention, express their view, and contest the decision", true, 1),
      o("C", "File a product-liability suit against the model vendor", false, 2),
      o("D", "Demand the bank publish the model's source code", false, 3),
    ],
    correctExplanation: "Art. 22 grants redress: human intervention, express a view, and contest the decision.",
    whyWrong: { A: "A right to recourse exists.", C: "Wrong legal track.", D: "Not a right under Art. 22." },
    trapType: "none",
    bokRef: "Domain II, Competency A",
    source: "authored",
  },
  {
    id: "q-ii-a-2",
    competencyId: "ii-a",
    type: "recall",
    difficulty: 2,
    stem: "Under GDPR Article 22, an exception to the general prohibition on solely automated decision-making includes:",
    isMultiselect: false,
    options: [o("A", "Implicit consent of the data subject", false, 0), o("B", "Necessity for fulfillment of a contract", true, 1), o("C", "Marketing convenience for the controller", false, 2), o("D", "Cost savings for the processor", false, 3)],
    correctExplanation: "Art. 22 exceptions: contract necessity, explicit consent, or authorizing law.",
    whyWrong: { A: "Consent must be EXPLICIT, not implicit.", C: "Not an exception.", D: "Not an exception." },
    trapType: "none",
    bokRef: "Domain II, Competency A",
    source: "community",
  },
  {
    id: "q-ii-b-1",
    competencyId: "ii-b",
    type: "not",
    difficulty: 2,
    stem: "A US manufacturer uses an algorithm to screen job applicants. Which source is LEAST likely to provide guidance on minimizing discrimination and bias in this use?",
    isMultiselect: false,
    options: [o("A", "The Americans with Disabilities Act (ADA)", false, 0), o("B", "The Fair Credit Reporting Act (FCRA)", false, 1), o("C", "The National Artificial Intelligence Initiative Act (NAIIA)", true, 2), o("D", "EEOC enforcement actions on automated employment tools", false, 3)],
    correctExplanation: "NAIIA is a federal R&D coordination act — it gives no anti-discrimination guidance.",
    whyWrong: { A: "ADA bears directly on disability discrimination in hiring.", B: "FCRA governs consumer-report use in employment.", D: "EEOC actions show the agency's view on automated-tool discrimination." },
    strategyNote: "The outlier is a real law applied to the wrong purpose. Know what each instrument is FOR.",
    trapType: "true-but-irrelevant",
    bokRef: "Domain II, Competency B",
    source: "authored",
  },
  {
    id: "q-ii-b-2",
    competencyId: "ii-b",
    type: "recall",
    difficulty: 1,
    stem: "The FTC's primary authority to regulate 'unfair or deceptive acts or practices' comes from:",
    isMultiselect: false,
    options: [o("A", "Section 5 of the FTC Act (1914)", true, 0), o("B", "The Civil Rights Act of 1964", false, 1), o("C", "COPPA (1998)", false, 2), o("D", "Section 230 of the CDA", false, 3)],
    correctExplanation: "Section 5 of the FTC Act is the unfair/deceptive-practices authority, applied to AI claims and undisclosed practices.",
    whyWrong: { B: "Anti-discrimination law, not FTC §5.", C: "Children's online privacy.", D: "Platform liability shield." },
    trapType: "none",
    bokRef: "Domain II, Competency B",
    source: "community",
  },
  {
    id: "q-ii-c-1",
    competencyId: "ii-c",
    type: "best",
    difficulty: 2,
    stem: "A company scrapes millions of facial images from public websites to build a general facial-recognition database it will license in the EU. Under the EU AI Act, this practice is:",
    isMultiselect: false,
    options: [
      o("A", "High-risk, requiring a conformity assessment", false, 0),
      o("B", "Limited-risk, requiring a transparency notice", false, 1),
      o("C", "Prohibited, exposing the firm to the top penalty tier (up to €35M or 7% of global turnover)", true, 2),
      o("D", "Minimal-risk, requiring only a voluntary code of conduct", false, 3),
    ],
    correctExplanation: "Untargeted facial-image scraping is a prohibited Art. 5 practice → top tier €35M/7%.",
    whyWrong: { A: "Under-classifies a prohibited practice as high-risk.", B: "Far too lenient.", D: "Far too lenient." },
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "authored",
  },
  {
    id: "q-ii-c-2",
    competencyId: "ii-c",
    type: "role",
    difficulty: 3,
    stem: "GenSys SA develops a CV-screening model and sells it across the EU under its own brand. Hirewell GmbH licenses it, uses it unchanged to filter its own applicants, then rebrands it as 'HireWell AI' and markets it to other employers. Under the EU AI Act, Hirewell is:",
    isMultiselect: false,
    options: [
      o("A", "Only a deployer, with no provider obligations", false, 0),
      o("B", "A distributor with no obligations", false, 1),
      o("C", "A provider, because rebranding a high-risk system makes it take on provider obligations", true, 2),
      o("D", "An importer, because it is EU-based", false, 3),
    ],
    correctExplanation: "Rebranding a high-risk system (Art. 25) makes the actor a provider with full provider obligations.",
    whyWrong: { A: "Ignores the rebrand.", B: "Understates obligations.", D: "Being EU-based doesn't make it an importer when it puts its own name on the system." },
    strategyNote: "Decide who built-and-placed vs who uses before reading the obligation options. Rebrand/substantial-mod ⇒ provider.",
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "authored",
  },
  {
    id: "q-ii-c-3",
    competencyId: "ii-c",
    type: "recall",
    difficulty: 2,
    stem: "A GPAI model is presumed to have systemic risk when training computation exceeds:",
    isMultiselect: false,
    options: [o("A", "10^15 FLOPs", false, 0), o("B", "10^20 FLOPs", false, 1), o("C", "10^25 FLOPs", true, 2), o("D", "10^30 FLOPs", false, 3)],
    correctExplanation: "The EU AI Act presumes systemic risk above 10^25 FLOPs of training compute.",
    whyWrong: { A: "Too low.", B: "Too low.", D: "Too high." },
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "community",
  },
  {
    id: "q-ii-c-4",
    competencyId: "ii-c",
    type: "best",
    difficulty: 2,
    stem: "An EU consumer-app maker adds an AI chat assistant. To comply with the EU AI Act transparency obligation, users must be told they are interacting with AI:",
    isMultiselect: false,
    options: [
      o("A", "In the terms of service accepted at sign-up months earlier", false, 0),
      o("B", "At the time of the first interaction or exposure to the system, in advance", true, 1),
      o("C", "In a notification sent after the first conversation ends", false, 2),
      o("D", "Only if a user explicitly asks whether it is AI", false, 3),
    ],
    correctExplanation: "Art. 50 requires disclosure at the first interaction/exposure, proactively.",
    whyWrong: { A: "Buried ToS isn't 'at first interaction'.", C: "After-the-fact fails the rule.", D: "Disclosure can't be on-request only." },
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "authored",
  },
  {
    id: "q-ii-c-5",
    competencyId: "ii-c",
    type: "recall",
    difficulty: 2,
    stem: "Under the South Korean AI Basic Act, the term used for AI that significantly affects human life, safety or fundamental rights in critical sectors is:",
    isMultiselect: false,
    options: [o("A", "High-risk AI", false, 0), o("B", "High-impact AI", true, 1), o("C", "Unacceptable-risk AI", false, 2), o("D", "Systemic AI", false, 3)],
    correctExplanation: "South Korea uses 'high-impact AI' (effective 22 Jan 2026), an innovation-first regime with no mandatory third-party conformity assessment.",
    whyWrong: { A: "'High-risk' is the EU AI Act term.", C: "'Unacceptable risk' is the EU prohibited tier.", D: "Systemic risk is the EU GPAI concept." },
    strategyNote: "EU = 'high-risk'; South Korea = 'high-impact'. Don't swap the vocabulary.",
    trapType: "synonym-bait",
    bokRef: "Domain II, Competency C",
    source: "authored",
  },
  {
    id: "q-ii-c-6",
    competencyId: "ii-c",
    type: "best",
    difficulty: 2,
    stem: "A company operating an AI image-generation platform asks how the US Take It Down Act affects it. The best summary is:",
    isMultiselect: false,
    options: [
      o("A", "It bans all generative-image AI in the US", false, 0),
      o("B", "It targets non-consensual intimate imagery, including AI deepfakes, and requires covered platforms to remove flagged content within 48 hours; build a notice-and-removal process", true, 1),
      o("C", "It only applies to social-media platforms, never to AI developers", false, 2),
      o("D", "It is a voluntary framework with no enforcement", false, 3),
    ],
    correctExplanation: "Take It Down Act (signed 19 May 2025) targets NCII incl. AI deepfakes; covered platforms must remove within 48 hours (FTC-enforced from 19 May 2026).",
    whyWrong: { A: "It doesn't ban generative AI.", C: "It reaches AI developers and platforms.", D: "It's enforceable law, not voluntary." },
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "authored",
  },
  {
    id: "q-ii-c-7",
    competencyId: "ii-c",
    type: "not",
    difficulty: 2,
    stem: "Which violation does NOT map to the EU AI Act's top €35M/7% penalty tier?",
    isMultiselect: false,
    options: [o("A", "Operating a social-scoring system", false, 0), o("B", "Untargeted scraping of facial images", false, 1), o("C", "Supplying incorrect information to a notified body", true, 2), o("D", "Deploying a prohibited manipulative AI system", false, 3)],
    correctExplanation: "Supplying incorrect information sits in the lowest tier (€7.5M/1%).",
    whyWrong: { A: "Prohibited practice → top tier.", B: "Prohibited practice → top tier.", D: "Prohibited practice → top tier." },
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "authored",
  },
  {
    id: "q-ii-c-8",
    competencyId: "ii-c",
    type: "recall",
    difficulty: 2,
    stem: "A system listed in Annex III may avoid high-risk classification under Article 6(3) if it:",
    isMultiselect: false,
    options: [o("A", "Performs only a narrow procedural task", true, 0), o("B", "Is sold below a market-price threshold", false, 1), o("C", "Is open-source under any license", false, 2), o("D", "Operates only inside the EU", false, 3)],
    correctExplanation: "Art. 6(3) carves out systems posing no significant risk (e.g., a narrow procedural task) — unless they profile natural persons.",
    whyWrong: { B: "Price is irrelevant.", C: "Open-source doesn't exempt from high-risk duties.", D: "Geography doesn't change the classification." },
    trapType: "none",
    bokRef: "Domain II, Competency C",
    source: "community",
  },
  {
    id: "q-ii-d-1",
    competencyId: "ii-d",
    type: "best",
    difficulty: 2,
    stem: "An AI team has identified false-positive spikes in a deployed fraud model, documented the incidents, analyzed root cause, and is now choosing between retraining and interim threshold controls. Which NIST AI RMF function are they exercising?",
    isMultiselect: false,
    options: [o("A", "MAP", false, 0), o("B", "MEASURE", false, 1), o("C", "MANAGE", true, 2), o("D", "GOVERN", false, 3)],
    correctExplanation: "Deciding how to respond (retrain vs interim controls) = MANAGE (prioritize and act).",
    whyWrong: { A: "MAP = identify context/risks.", B: "MEASURE = assess/track.", D: "GOVERN = culture/policy." },
    trapType: "none",
    bokRef: "Domain II, Competency D",
    source: "authored",
  },
  {
    id: "q-ii-d-2",
    competencyId: "ii-d",
    type: "distinction",
    difficulty: 1,
    stem: "Which instrument is legally binding and imposes mandatory compliance?",
    isMultiselect: false,
    options: [o("A", "The OECD AI Principles", false, 0), o("B", "The NIST AI Risk Management Framework", false, 1), o("C", "The EU AI Act", true, 2), o("D", "The White House Blueprint for an AI Bill of Rights", false, 3)],
    correctExplanation: "Only the EU AI Act is binding law; the others are voluntary guidance.",
    whyWrong: { A: "Voluntary international guidance.", B: "Voluntary framework.", D: "Non-binding US guidance." },
    strategyNote: "Voluntary vs mandatory is a recurring trap. NIST/OECD/ISO = voluntary; EU AI Act = mandatory.",
    trapType: "none",
    bokRef: "Domain II, Competency D",
    source: "authored",
  },
  {
    id: "q-ii-d-3",
    competencyId: "ii-d",
    type: "not",
    difficulty: 1,
    stem: "Which is NOT one of NIST AI RMF's characteristics of trustworthy AI?",
    isMultiselect: false,
    options: [o("A", "Valid and reliable", false, 0), o("B", "Privacy-enhanced", false, 1), o("C", "Profit-maximizing", true, 2), o("D", "Secure and resilient", false, 3)],
    correctExplanation: "'Profit-maximizing' is not a NIST trustworthy-AI characteristic.",
    whyWrong: { A: "One of the seven.", B: "One of the seven.", D: "One of the seven." },
    trapType: "none",
    bokRef: "Domain II, Competency D",
    source: "community",
  },
  {
    id: "q-ii-d-4",
    competencyId: "ii-d",
    type: "recall",
    difficulty: 1,
    stem: "ISO/IEC 42001:2023 is described as a 'Type A' standard, meaning it:",
    isMultiselect: false,
    options: [o("A", "Applies only to high-risk AI systems", false, 0), o("B", "Can be certified by a third party", true, 1), o("C", "Is mandatory in the EU", false, 2), o("D", "Replaces ISO/IEC 27001", false, 3)],
    correctExplanation: "ISO/IEC 42001 is a certifiable AI management-system standard (like ISO 27001).",
    whyWrong: { A: "Applies to AI management broadly.", C: "Voluntary, not mandatory.", D: "Complements, not replaces, 27001." },
    trapType: "none",
    bokRef: "Domain II, Competency D",
    source: "community",
  },

  // ───────────── DOMAIN III ─────────────
  {
    id: "q-iii-a-1",
    competencyId: "iii-a",
    type: "ordering",
    difficulty: 2,
    stem: "Put these AI-planning steps in the correct order: (1) identify the data needed; (2) determine the business problem; (3) identify applicable laws; (4) determine specific use cases; (5) identify use-case gaps and risks.",
    isMultiselect: false,
    options: [
      o("A", "2 → 4 → 3 → 5 → 1", true, 0),
      o("B", "1 → 2 → 3 → 4 → 5", false, 1),
      o("C", "2 → 1 → 4 → 3 → 5", false, 2),
      o("D", "4 → 2 → 1 → 5 → 3", false, 3),
    ],
    correctExplanation: "Business problem → use cases → applicable laws → gaps & risks → data needed. Data/model choices come last.",
    whyWrong: { B: "Puts data first.", C: "Puts data before use cases/laws.", D: "Scrambles the front." },
    strategyNote: "Ordering questions: business/governance/legal BEFORE technical.",
    trapType: "none",
    bokRef: "Domain III, Competency A",
    source: "authored",
  },
  {
    id: "q-iii-b-1",
    competencyId: "iii-b",
    type: "best",
    difficulty: 1,
    stem: "Which method best ensures training data is accurate, representative, and unbiased?",
    isMultiselect: false,
    options: [o("A", "Assuming purchased vendor data is accurate", false, 0), o("B", "Tracking data lineage and provenance", true, 1), o("C", "Maximizing the number of features regardless of relevance", false, 2), o("D", "Using the same set for training and testing", false, 3)],
    correctExplanation: "Data lineage/provenance tracks data from source through transformations to the model — ensuring it's accurate and appropriate.",
    whyWrong: { A: "Never assume accuracy.", C: "Risks overfitting and violates minimization.", D: "Causes overfitting." },
    trapType: "absolute",
    bokRef: "Domain III, Competency B",
    source: "authored",
  },
  {
    id: "q-iii-b-2",
    competencyId: "iii-b",
    type: "distinction",
    difficulty: 2,
    stem: "An insurer trains a fraud model on five years of historical claims; after launch it under-detects fraud on mobile-app claims because the training period predates mobile adoption. This is best described as:",
    isMultiselect: false,
    options: [o("A", "Sampling bias", false, 0), o("B", "Temporal bias", true, 1), o("C", "Confirmation bias", false, 2), o("D", "Projection bias", false, 3)],
    correctExplanation: "Data unbalanced over time (pre-mobile era) = temporal bias.",
    whyWrong: { A: "Sampling = bad sample selection.", C: "Confirmation = seeking confirming data.", D: "Projection = assuming others share your preferences." },
    trapType: "none",
    bokRef: "Domain III, Competency B",
    source: "authored",
  },
  {
    id: "q-iii-b-3",
    competencyId: "iii-b",
    type: "distinction",
    difficulty: 2,
    stem: "Three hospitals want to train a shared model without pooling patient records in one place. Which privacy-enhancing technique best fits?",
    isMultiselect: false,
    options: [o("A", "Differential privacy", false, 0), o("B", "Homomorphic encryption", false, 1), o("C", "Federated learning", true, 2), o("D", "Pseudonymization", false, 3)],
    correctExplanation: "Federated learning trains at each site; raw data never moves.",
    whyWrong: { A: "Adds noise; doesn't prevent data movement.", B: "Computes on encrypted data, not the distributed-training problem here.", D: "Just de-identifies; data still moves." },
    trapType: "none",
    bokRef: "Domain III, Competency B",
    source: "authored",
  },
  {
    id: "q-iii-c-1",
    competencyId: "iii-c",
    type: "distinction",
    difficulty: 2,
    stem: "A bank must investigate an incident on a deployed model and needs system documentation, the incident-response plan, data dictionaries, source-code links, and AI-actor contacts. Which artifact holds these?",
    isMultiselect: false,
    options: [o("A", "The model card", false, 0), o("B", "The risk assessment", false, 1), o("C", "The AI system inventory", true, 2), o("D", "The privacy impact assessment", false, 3)],
    correctExplanation: "The AI system inventory is the full governance repository (docs, incident plans, data dictionaries, source-code links, actor contacts).",
    whyWrong: { A: "A model card is a behavior/use summary.", B: "Lists risks/mitigations only.", D: "Privacy-focused." },
    strategyNote: "Model card (summary) ≠ AI system inventory (full artifact repository).",
    trapType: "synonym-bait",
    bokRef: "Domain III, Competency C",
    source: "authored",
  },
  {
    id: "q-iii-c-2",
    competencyId: "iii-c",
    type: "distinction",
    difficulty: 2,
    stem: "A security team has specialists actively attempt to manipulate a customer-support chatbot into leaking account data and bypassing safety filters. This activity is:",
    isMultiselect: false,
    options: [o("A", "Threat modeling", false, 0), o("B", "An audit", false, 1), o("C", "Red teaming", true, 2), o("D", "A privacy impact assessment", false, 3)],
    correctExplanation: "Active adversarial attack simulation = red teaming.",
    whyWrong: { A: "Threat modeling maps threats; no live attack.", B: "Audits check compliance/consistency.", D: "A PIA assesses privacy." },
    trapType: "synonym-bait",
    bokRef: "Domain III, Competency C",
    source: "authored",
  },
  {
    id: "q-iii-c-3",
    competencyId: "iii-c",
    type: "recall",
    difficulty: 1,
    stem: "Which step comes AFTER development is complete but BEFORE deployment, to confirm the system is fit to go live?",
    isMultiselect: false,
    options: [o("A", "Defining the business problem", false, 0), o("B", "Collecting training data", false, 1), o("C", "A readiness assessment (incl. the model card and conformity checks)", true, 2), o("D", "Selecting the model architecture", false, 3)],
    correctExplanation: "A readiness assessment sits after development, before deployment.",
    whyWrong: { A: "Earliest planning step.", B: "A development step.", D: "A design step." },
    trapType: "none",
    bokRef: "Domain III, Competency C",
    source: "authored",
  },

  // ───────────── DOMAIN IV ─────────────
  {
    id: "q-iv-a-1",
    competencyId: "iv-a",
    type: "distinction",
    difficulty: 1,
    stem: "A streaming service builds a feature that uses each subscriber's full viewing history and preferences to assemble a homepage unique to that person. This use case is:",
    isMultiselect: false,
    options: [o("A", "Detection", false, 0), o("B", "Recognition", false, 1), o("C", "Optimization", false, 2), o("D", "Personalization", true, 3)],
    correctExplanation: "A unique experience built from an individual profile = personalization.",
    whyWrong: { A: "Detection finds anomalies/events.", B: "Recognition matches to a known catalog/identity.", C: "Optimization improves a process." },
    trapType: "none",
    bokRef: "Domain IV, Competency A",
    source: "authored",
  },
  {
    id: "q-iv-a-2",
    competencyId: "iv-a",
    type: "distinction",
    difficulty: 2,
    stem: "A bank in 47 countries lets each country team manage AI risk locally while a central committee at HQ sets policy and handles the highest-risk escalations. This is:",
    isMultiselect: false,
    options: [o("A", "Centralized", false, 0), o("B", "Decentralized", false, 1), o("C", "Hybrid", true, 2), o("D", "Outsourced", false, 3)],
    correctExplanation: "Local execution + central policy/escalation = hybrid governance (best for large multinationals).",
    whyWrong: { A: "Centralized = all at HQ.", B: "Decentralized = no central coordination.", D: "Not a governance model." },
    trapType: "none",
    bokRef: "Domain IV, Competency A",
    source: "authored",
  },
  {
    id: "q-iv-a-3",
    competencyId: "iv-a",
    type: "recall",
    difficulty: 1,
    stem: "A company deploys a model to smartphones to cut latency and keep user data local. What deployment environment is this?",
    isMultiselect: false,
    options: [o("A", "Cloud", false, 0), o("B", "On premise", false, 1), o("C", "Edge", true, 2), o("D", "Local API only", false, 3)],
    correctExplanation: "On-device processing to cut latency and keep data local = edge deployment.",
    whyWrong: { A: "Cloud is remote.", B: "On-prem is the org's own servers.", D: "Not a deployment environment." },
    trapType: "none",
    bokRef: "Domain IV, Competency A",
    source: "community",
  },
  {
    id: "q-iv-b-1",
    competencyId: "iv-b",
    type: "not",
    difficulty: 2,
    stem: "An organization reviews an open-source AI model's agreement for data privacy and IP compliance. Which term is LEAST critical to that specific goal?",
    isMultiselect: false,
    options: [o("A", "Training-data ownership and usage rights", false, 0), o("B", "Output ownership", false, 1), o("C", "Obligations to share derivative works", false, 2), o("D", "The vendor's logo and co-marketing rights", true, 3)],
    correctExplanation: "Logo/co-marketing rights are commercial branding — irrelevant to data-privacy/IP compliance.",
    whyWrong: { A: "Directly drives IP/copyright exposure.", B: "Critical for IP.", C: "Critical for open-source licenses." },
    trapType: "true-but-irrelevant",
    bokRef: "Domain IV, Competency B",
    source: "authored",
  },
  {
    id: "q-iv-b-2",
    competencyId: "iv-b",
    type: "best",
    difficulty: 2,
    stem: "A team is told 'our tech stack (frameworks and libraries) determines which laws apply.' The best correction is:",
    isMultiselect: false,
    options: [
      o("A", "Correct — the tech stack determines applicable law", false, 0),
      o("B", "Applicable law is driven by jurisdiction, sector, data type, and use case — not the tech stack itself", true, 1),
      o("C", "No laws apply to internally built tools", false, 2),
      o("D", "Only copyright law ever applies to AI", false, 3),
    ],
    correctExplanation: "Applicable law follows jurisdiction, sector, data type, and use — not the technology stack.",
    whyWrong: { A: "Repeats the error.", C: "False.", D: "False." },
    trapType: "none",
    bokRef: "Domain IV, Competency B",
    source: "authored",
  },
  {
    id: "q-iv-c-1",
    competencyId: "iv-c",
    type: "best",
    difficulty: 2,
    stem: "An AI fraud system produces excessive false positives due to data drift. The team identifies and applies a feasible threshold-adjustment mitigation promptly. What best justifies keeping the system running rather than deactivating it?",
    isMultiselect: false,
    options: [
      o("A", "The system has been profitable for three years", false, 0),
      o("B", "Migrating data to a replacement would be burdensome", false, 1),
      o("C", "A feasible mitigation was identified and implemented in a timely manner", true, 2),
      o("D", "The system's limitations are documented for customers", false, 3),
    ],
    correctExplanation: "A timely, feasible mitigation justifies continued operation.",
    whyWrong: { A: "Profit is never a valid justification.", B: "Migration burden is invalid economics.", D: "Documentation alone doesn't fix performance." },
    strategyNote: "Watch 'wrong-economics' distractors (profit/cost) in deactivation questions.",
    trapType: "wrong-economics",
    bokRef: "Domain IV, Competency C",
    source: "authored",
  },
  {
    id: "q-iv-c-2",
    competencyId: "iv-c",
    type: "not",
    difficulty: 2,
    stem: "Which is NOT a valid trigger in a deactivation/localization policy?",
    isMultiselect: false,
    options: [
      o("A", "A new regulatory requirement the system cannot meet", false, 0),
      o("B", "Significant, unmitigated performance failures", false, 1),
      o("C", "A desire to protect the product's profit margin", true, 2),
      o("D", "A legal order to stop processing in a jurisdiction", false, 3),
    ],
    correctExplanation: "Protecting profit is never a valid deactivation trigger.",
    whyWrong: { A: "Regulatory inability is valid.", B: "Unmitigated failure is valid.", D: "A legal order is valid." },
    trapType: "wrong-economics",
    bokRef: "Domain IV, Competency C",
    source: "authored",
  },
  {
    id: "q-iv-c-3",
    competencyId: "iv-c",
    type: "best",
    difficulty: 2,
    stem: "A provider must keep an AI feature offline in one country during regulatory negotiations while keeping it live elsewhere, ideally without a full redeploy. The best mechanism is:",
    isMultiselect: false,
    options: [o("A", "Permanently deleting the model", false, 0), o("B", "Jurisdiction-scoped feature flags", true, 1), o("C", "Emailing users to ignore the feature", false, 2), o("D", "Waiting for the next major release", false, 3)],
    correctExplanation: "Jurisdiction-scoped feature flags disable a feature in one country without a redeploy.",
    whyWrong: { A: "Destructive and disproportionate.", C: "Ineffective.", D: "Too slow." },
    trapType: "none",
    bokRef: "Domain IV, Competency C",
    source: "authored",
  },
  {
    id: "q-iv-c-4",
    competencyId: "iv-c",
    type: "best",
    difficulty: 1,
    stem: "Which is the recognized best-practice artifact for forecasting and limiting an AI model's secondary or unintended uses?",
    isMultiselect: false,
    options: [o("A", "The marketing brief", false, 0), o("B", "The model card", true, 1), o("C", "The data-retention schedule", false, 2), o("D", "The org chart", false, 3)],
    correctExplanation: "Model cards are the recognized best practice for forecasting and limiting secondary/unintended use.",
    whyWrong: { A: "Irrelevant.", C: "Irrelevant.", D: "Irrelevant." },
    trapType: "none",
    bokRef: "Domain IV, Competency C",
    source: "community",
  },
];
